(cl:defpackage pal_detection_msgs-msg
  (:use )
  (:export
   "<LEGDETECTIONS>"
   "LEGDETECTIONS"
   "<FACEDETECTION>"
   "FACEDETECTION"
   "<ROTATEDDETECTION2D>"
   "ROTATEDDETECTION2D"
   "<RECOGNIZEDACTIONS>"
   "RECOGNIZEDACTIONS"
   "<PERSONDETECTIONS>"
   "PERSONDETECTIONS"
   "<PERSONDETECTION>"
   "PERSONDETECTION"
   "<FACEDETECTIONS>"
   "FACEDETECTIONS"
   "<DETECTIONS2D>"
   "DETECTIONS2D"
   "<WAVEDETECTION>"
   "WAVEDETECTION"
   "<DETECTION2D>"
   "DETECTION2D"
   "<TEXTUREDOBJECTDETECTION>"
   "TEXTUREDOBJECTDETECTION"
  ))

