(cl:defpackage pal_video_recording_msgs-srv
  (:use )
  (:export
   "STOPRECORDING"
   "<STOPRECORDING-REQUEST>"
   "STOPRECORDING-REQUEST"
   "<STOPRECORDING-RESPONSE>"
   "STOPRECORDING-RESPONSE"
   "STARTRECORDING"
   "<STARTRECORDING-REQUEST>"
   "STARTRECORDING-REQUEST"
   "<STARTRECORDING-RESPONSE>"
   "STARTRECORDING-RESPONSE"
  ))

