from ._Detections2d import *
from ._Detection2d import *
from ._FaceDetections import *
from ._PersonDetections import *
from ._RotatedDetection2d import *
from ._LegDetections import *
from ._TexturedObjectDetection import *
from ._PersonDetection import *
from ._RecognizedActions import *
from ._FaceDetection import *
from ._WaveDetection import *
